### ISSUE TITLE
MoNuSeg(mat)

### ISSUE THREAD

**Issue by happywt** [ChakiCurtin/INSBench#1]
Author Hello, my MoNuSeg dataset annotation format is mat format, how to convert it to coco format?  Can you provide the MoNuSeg dataset in coco format? Thanks！

**Comment by chasercodeio** [comment]
Hi @happywt , thanks for the question. Regarding mat format, I am not very familiar with it and so will not be able to help you there. However, I have provided my Google Drive link to the MoNuSeg dataset in Yolo darknet format [here](https://drive.google.com/file/d/1a_SQvg4RFVTpP0W5E9V4JEp2dwf45fxh/view?usp=sharing). 

Once you download and extract the dataset, the files you need are under the "./MoNuSeg/yolo/" directory. Please use my other [GitHub repo](https://github.com/ChakiCurtin/YOLO-SEG-to-COCO-Converter/tree/main) created to help convert from yolo darknet annotation format to COCO format. 

The process of converting from darknet annotation to COCO is quite simple, and all the instructions are included in that repo.

1. Clone that repository to your computer
2. use the classes.txt file found in the demo folder as part of the Python script (made for MoNuSeg).
3. Run the script as per the instructions in the repo under "Testing | Demo" and "Actual Usage". 
4. Once you test it to make sure all the annotations are as expected, you can save the coco formatted annotation files:
- python3 yolo-to-coco.py --dataset ./MoNuSeg/yolo/train/ --classes ./demo/classes.txt --save ./output/train.json
- python3 yolo-to-coco.py --dataset ./MoNuSeg/yolo/test/ --classes ./demo/classes.txt --save ./output/test.json
- python3 yolo-to-coco.py --dataset ./MoNuSeg/yolo/val/ --classes ./demo/classes.txt --save ./output/val.json

Hope this helped you. The current train.json in the output folder is only for those 2 images I think. Your train.json file, when created, should be quite a big file with annotations for all images under the train directory.

**Comment by happywt** [comment]
@ChakiCurtin Thank you. Thank you very much. This is very useful for me! Thanks again!
